services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      # Ensure DATABASE_URL is set correctly in your .env file
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # Ensure POSTGRES_PASSWORD is set to a strong value in your environment or use Docker secrets for production
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
  app_node_modules:
