services:
  app:
    build:
      context: ./apps/next-app
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - ./apps/next-app:/app
      - app_node_modules:/app/node_modules
      - app_next:/app/.next
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL}
      WATCHPACK_POLLING: "true"
      NEXT_PUBLIC_WS_URL: ws://localhost:8080
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  app_node_modules:
  app_next:
  db_data:

networks:
  app-network:
    driver: bridge
